name: Build docker image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        docker build . -t jedie/esp-open-sdk:latest
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push jedie/esp-open-sdk;
